### ISSUE TITLE
Custom selection of VIP features

### ISSUE THREAD

**Issue by alex-d13** [interactivereport/cellxgene_VIP#104]
Hi,

I am trying to setup VIP for a large group of users and in order to not overwhelm them and keeping our server resources in check, I wanted to only enable a few selected visualization features in cellxgene VIP, for example violin plots, DGE and heatmaps. I am a bit scared that users will do resource intensive things with the command line feature.

So my question is: is it possible to enable/disable specific features of cellxgene VIP? Would it be enough to create a forked repository and remove a few options from the menu?
I was hoping to get your input here :)

Best wishes,
Alex

**Comment by nictru** [comment]
I think the sections can be disabled by commenting out blocks like [this](https://github.com/interactivereport/cellxgene_VIP/blob/6cdf7f603c6d8f7b1dfa728c9dcaa86a6e547bdd/interface.html#L768)

**Comment by interactivereport** [comment]
We will add a line in description text file so analyst can disable features.

**Comment by z5ouyang** [comment]
The functionality ("Disable Panel") is added:
1. Create a text file the same as the h5ad with file extension ".txt" instead of ".h5ad", in the same folder as h5ad;
2. The information of this text file will be displayed in the cellxgene left panel between "categorical" and "numerical" variable;
3. If a line in the text starts with "Disable Panel", side buttons (listed in the text file) in the VIP will NOT be shown, such as: 
```Disable Panel: Command Line Interface, Spatial Transcriptomics```
4. If a line in the text starts with "Initial Embedding", the data will use the specified embedding when user initially access the page , such as: 
```Initial Embedding: harmony_UMAP```
5. If a line in the text starts with "Initial Coloring", the data will use the specified annotation to color the cells when user initially access the page , such as: 
```Initial Coloring: cell_type```

Please reopen if you have any additional questions
