### ISSUE TITLE
VIP not adding genes on Large Dataset (~100K cells)

### ISSUE THREAD

**Issue by wariobrega** [interactivereport/cellxgene_VIP#25]
Hello,

cellXgene VIP works fantastically on all datasets I have but one that is bigger than the others (~100k cells).
In particular, what it happens is that the cellXgene VIP plugin appears but the "add Gene" panel is blank at first.

I get the following error from the web consoles:
![image](https://user-images.githubusercontent.com/10073781/94719295-459cb980-0353-11eb-9b00-c6d08a3c0879.png)

Moreover, when I try to add a gene (that I know) I obtain the following error from console:
![image](https://user-images.githubusercontent.com/10073781/94719511-8a285500-0353-11eb-9aad-320560df2f33.png)

One last info: the "gene is not present in the "add gene" panel appears if I insert a gene that is not there, it simply DOES NOT  add the gene.

Can you help me out?

D.

**Comment by likejie** [comment]
Hi  @wariobrega, thanks for raise your issue! The framework handles million cells without problem based on our test.

Your issue could very likely due to your metadata contains some nans. We saw similar behavior before. Please refer to the end of our preprint which proposed a solution to remove nans by casting the annotation to str first and then replace all nans by 'nan'. That should help.  Please let us know if this solves your problem or not.

![image](https://user-images.githubusercontent.com/1277932/94720592-acee4580-0322-11eb-93de-d0b638b81400.png)

**Comment by wariobrega** [comment]
Hi @likejie I can confirm that was the issue indeed :)

Thanks a lot!

**Comment by likejie** [comment]
Glad it helped @wariobrega ! Cheers!
