### ISSUE TITLE
How to add description to my cellxgene?

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#40]
Hi, Is there is a way how to add description to my cellxgene instance ?
such as in the below instance
https://cellxgenevip-ms.bxgenomics.com/

**Comment by z5ouyang** [comment]
Yes. A description file within the same folder as your h5ad file but file extension is 'txt'. All content in the file will be shown, with some interpretation by VIP:

Description: Human brain snRNAseq 46k cells (MS Nature 2019 Schirmer et al.)
Platform: 10X 3' v2 chemistry nuclear sequencing
Data: normalized, log transformed UMI
Initial Embedding: umap_harmony
Initial Coloring: cell_type

"initial Embedding": VIP will use this for initial visualization embedding instead the first default one;
"Initial Coloring": VIP will use the annotation to color the cells instead of all black.

Please feel free to reopen this if you have problems to set it up.

**Comment by FADHLyemen** [comment]
what is the name of this txt file, is it same h5ad name?

**Comment by z5ouyang** [comment]
Correct, the same as the h5ad file name (whatever.name.of.your.h5ad), with 'txt' extension as whatever.name.of.your.txt in the same folder.
