### ISSUE TITLE
why number of cells in violin and dot plot are not similar ?

### ISSUE THREAD

**Issue by FADHLyemen** [interactivereport/cellxgene_VIP#52]
Hi, 
for cut off =1, I got different number of cells in dot and violin plot
I used your example:
https://cellxgenevip-ms.bxgenomics.com/
Viloin plot, groupby "louvian_harmaony"
![image](https://user-images.githubusercontent.com/23288387/121633607-1a757880-ca51-11eb-8708-f46f7740706b.png)

dot plot, groupby "louvian_harmaony"
![image](https://user-images.githubusercontent.com/23288387/121633651-2feaa280-ca51-11eb-9489-1b0616b89229.png)

I do not know why VIP violin plot is different?
In scanpy, I got the same number of cells in bot plot using the below code:

```
ax = sc.pl.stacked_violin(adata, ['ACE2'], groupby=['louvain'], 
                          swap_axes=False, dendrogram=False,
                         figsize=(4, 8),return_fig=True,
                          expression_cutoff =1,yticklabels=True
                                                   )
ax.add_totals().show()
```
```
ax = sc.pl.dotplot(adata, ['ACE2'], groupby=['louvain'], 
                          swap_axes=False, dendrogram=False,
                         figsize=(4, 8),return_fig=True,
                          expression_cutoff =1,yticklabels=True
                                                   )
ax.add_totals().show()
```

**Comment by FADHLyemen** [comment]
VIP code for violin plot
![image](https://user-images.githubusercontent.com/23288387/121712285-93a0ba00-caa9-11eb-97a7-99b0741f3e30.png)
VIP code for dot plot
![image](https://user-images.githubusercontent.com/23288387/121712334-a4e9c680-caa9-11eb-9d1a-9207d513c766.png)

**Comment by z5ouyang** [comment]
Thanks for the detailed report. Although the two used the same text in the web interface as "Expression cutoff", they are actually different:
stack_violin: (we added the filtering step) actually remove the cells from the plot if the max expression of all genes is lower (not equal) than the cutoff;
dot_plot: (scanpy parameters) does NOT remove any cells, but the threshold to determine the cell fraction which express the genes, represented as the size of the dot.

Thus, if you use '-0.01' for violin, you will get the same cell number as dot plot.

In order to clear the confusion, we updated the text on the user interface:
for violin as: Expression cutoff for cell filtering
for dot as: Expression cutoff for cell fraction (dot size)

Please feel free to reopen this, if you have additional questions related to this.
Thanks again!

**Comment by FADHLyemen** [comment]
Thank you for your response.
I can replicate the code for the dotplot as below:

```
ax = sc.pl.dotplot(adata, ['ACE2'], groupby=['louvain'], 
                          swap_axes=False, dendrogram=False,
                         figsize=(4, 8),return_fig=True,
                          expression_cutoff =1,yticklabels=True
                                                   )
ax.add_totals().show()
```
could you help me to replicate it for the stacked violin plot?

```
adata=geneFiltering(adata,1,1)
ax = sc.pl.stacked_violin(adata, ['ACE2'], groupby=['louvain'], 
                          swap_axes=False, dendrogram=False,
                         figsize=(4, 8),return_fig=True,
                          expression_cutoff =1,yticklabels=True
                                                   )
ax.add_totals().show()

```

I do not know why I still get the same number of cells from `geneFiltering()`

**Comment by z5ouyang** [comment]
The reason 'geneFiltering' didn't remove any cells, is because you used the whole set genes. As I stated in the previous message: "actually remove the cells from the plot if the max expression of all genes is lower (not equal) than the cutoff", if you provide the full gene list in "adata", I assume there will be a gene in any cell will be larger than 1, which results that no cell will be removed.

If you want to repeat what VIP did, you can:
```
subD = adata[:,['ACE2']] 
subD=geneFiltering(subD,1,1)
ax = sc.pl.stacked_violin(subD, ['ACE2'], groupby=['louvain'], 
                          swap_axes=False, dendrogram=False,
                         figsize=(4, 8),return_fig=True,
                          expression_cutoff =1,yticklabels=True
                                                   )
ax.add_totals().show()
```
The first line is subset the whole dataset with only one gene "ACE2". This way, the cells whose "ACE2" expression below your cutoff will be filtered out.

Hope this helps.
