### ISSUE TITLE
VIP Visualization in Plugin

### ISSUE THREAD

**Issue by xxlovexx1314** [interactivereport/cellxgene_VIP#59]
Hi Young, 
     After I updated the VIPInterface.sh recently, I still meet the visualization problems, as the following picture:
![cf87707f2adb76724cc5ae78e4682f0](https://user-images.githubusercontent.com/57085980/138386536-39d7ec32-d9fd-4996-91c9-5e4336afaa9e.png)
e:
     Any suggestions?

**Comment by z5ouyang** [comment]
It might be caused by the page was opened without any interaction for too long. Does other plotting functions work?

You can also "git pull" the newest version, activate your env, and run "./update.VIPInterface.sh once". And let me know if this helps.

**Comment by xxlovexx1314** [comment]
I updated to the newest version, but it was not fixed. Does it matter with the JSPANEL?
![5f47b1cb9d4fc4463fde2fb0eb47f51](https://user-images.githubusercontent.com/57085980/149454039-eef515d0-05d5-456e-9d17-d9031004a8ca.png)

**Comment by z5ouyang** [comment]
@xxlovexx1314 sorry for the delay. Please "@" my name when you reply, so I can get notification.
Do you still have issue? or did you try reinstall from fresh?
thanks

**Comment by eusebiu** [comment]
@z5ouyang I also get this error after building the VIP. I use the cellxgene gateway from Novartis and I noticed some errors in console:
       POST http://127.0.0.1:5005/view/pbmc3k.h5ad/VIP 500 (INTERNAL SERVER ERROR)
and when I try to use the plugin, I get:
Failed to load resource: the server responded with a status of 405 (METHOD NOT ALLOWED)

Any ideas what could go wrong?

**Comment by z5ouyang** [comment]
Hi all, If this error shows on the initial loading, (rather than for each plot). The reason might be the version of "anndata" used to create h5ad files. Currently VIP uses anndata "0.7.4". 
We are working on updating the VIP to align with newer cellxgene version (removed a function we need) which uses newer anndata version.

**Comment by Dane-Z** [comment]
I was able to fix the 405 error using the solution from #35 (updating cellxgene-vip). However, I'm still running an older version of cellxgene to use cellxgene-vip because errors are thrown when launching certain datasets, or the VIP plugin doesn't showup, if using the newest version of cellxgene. 

Very much looking forward to that update!

**Comment by eusebiu** [comment]
> Hi all, If this error shows on the initial loading, (rather than for each plot). The reason might be the version of "anndata" used to create h5ad files. Currently VIP uses anndata "0.7.4". We are working on updating the VIP to align with newer cellxgene version (removed a function we need) which uses newer anndata version.

@z5ouyang Any updates on when it will be available (the support for new cellxgene)? We are looking into starting a project and we would like to know which versions (of cellxgene and VIP) should we target.

**Comment by z5ouyang** [comment]
@eusebiu @Dane-Z 
If you run "config.sh" again in your conda env. will be using cellxgene v1.1.1

**Comment by eusebiu** [comment]
Thanks a lot!

**Comment by coopertdx** [comment]
I also encountered this problem in the latest version, but I solved it by going to cellxgene in the browser (rather than clicking a link from the console)
