### ISSUE TITLE
DEG in v1.1.1  ValueError: kth(=####)

### ISSUE THREAD

**Issue by dfermin** [interactivereport/cellxgene_VIP#89]
Hello

I'm trying to use the latest release of cellxgene_VIP (v.1.1.1) with my data which had been working with v.1.0.1.
When I select to regions of cells to do differential analysis I click on DEG and get this error:
```
ERROR @server: ValueError: kth(=1838) out of bounds (1838).
```

I've checked and I get this same error with any H5AD object I use. 

Do you have solution for how I could fix this?
Thank you.

![Screenshot 2023-02-28 at 3 10 26 PM](https://user-images.githubusercontent.com/3055867/221967462-9996b347-c1f8-4411-8b1a-302fce4c4569.png)

**Comment by z5ouyang** [comment]
Hi @dfermin, Thanks for using VIP and report the issue! We checked, and this bug was introduced by multiomics data. It should be fixed by 25d8b30c504d81260f4ee6a5cdd17a1e73b417ae. Please pull the latest code and run "update.VIPInterface.sh" under the corresponding env.
Please let us know if it didn't fix the issue!
Thanks!
